#!/bin/bash

if [ -z "$1" ]; then
  echo "usage: $0 <user@host> [<public key>]"
  exit 1
fi

key_file=~/.ssh/id_dsa.pub
[ -z "$2" ] || key_file=$2
key=$(<$key_file)

echo $key

ssh $1 <<EOF
mkdir -p .ssh
chmod 700 .ssh
cd .ssh
echo $key >>authorized_keys
chmod 600 authorized_keys
EOF
