#!/bin/bash

remote="$1"
shift
key="$@"

if [ -z "$remote" ]; then
  echo "usage: $0 <user@host> [<public key or public key file>]"
  exit 1
fi

if [ -z "$key" ]; then
  key=$(<~/.ssh/id_dsa.pub)
elif [ -e "$key" ]; then
  key=$(<$key)
fi

echo $key

ssh $remote <<EOF
mkdir -p .ssh
chmod 700 .ssh
cd .ssh
grep "$key" authorized_keys >/dev/null 2>&1 || echo $key >>authorized_keys
chmod 600 authorized_keys
EOF
