#!/usr/bin/env ruby

require 'rubygems'

if ARGV.size != 2 and ARGV.size != 3
  raise "usage: #$0 <user> <password> [<dump file to load>]"
end

user, password, dump_file = ARGV
database = user

if ENV["MYSQL_PASSWORD"]
  root_password = ENV["MYSQL_PASSWORD"]
else
  require 'highline/import'
  root_password = ask("Mysql root password: ") { |q| q.echo = false }
end

IO.popen("mysql -u root --password=\"#{root_password}\"", "w") do |f|
  f.puts "CREATE DATABASE `#{database}` DEFAULT CHARACTER SET `utf8` COLLATE `utf8_general_ci`;"
  f.puts "GRANT ALL PRIVILEGES ON #{database}.* TO '#{user}'@'localhost' IDENTIFIED BY '#{password}' WITH GRANT OPTION;"
end

if dump_file
  command = "mysql -u #{user} --password=\"#{password}\" #{user} <#{dump_file}"
  puts command
  system command
end
