#!/bin/sh

if [ $# -lt 2 ]; then
  echo "usage: $0 <user@hostname> <path> [<git init options...>]"
  exit 1
fi

remote="$1"
shift
path="$1"
shift
options="$@"

ssh $remote <<EOF
  set -x
  mkdir -p $path
  cd $path
  git init $options
EOF
