#!/bin/sh

host="$1"
repository="$2"
dir="$3"

if [ -z "$host" -o -z "$repository" -o -z "$dir" ]; then
  echo "$0 <user@host> <repository> <destination directory>"
  exit 1
fi

hook=".git/hooks/post-receive"

repo_host=`echo "$repository" |sed -e 's|.\+@\(.\+\):.\+|\1|'`
key=`ssh-keyscan -H $repo_host`

if [ -z "$key" ]; then
  echo "could not get key"
  exit 1
fi

ssh -t $host <<EOF
  echo key...
  grep '$key' .ssh/known_hosts >/dev/null || echo '$key' >.ssh/known_hosts
  echo clone...
  git clone $repository $dir
  echo create hook
  set -e
  cd $dir
  cat >$hook <<EOF2
#!/bin/sh
cd ..
unset GIT_DIR
git reset --hard
EOF2
  chmod +x $hook
  git config receive.denyCurrentBranch ignore
EOF
