#!/bin/sh

if [ $# != 4 ]; then
  echo "usage: $0 <login> <password> <root> <local user>"
  exit 1
fi

user="$1"
password="$2"
root="$3"
local_user="$4"

sudo htpasswd -b /etc/vsftpd.passwd "$user" "$password"
cat <<EOF | sudo tee "/etc/vsftpd.users/$user"
local_root=$root
guest_username=$local_user
EOF

sudo /etc/init.d/vsftpd restart
