#!/bin/sh

host="$1"
repository="$2"

if [ -z "$host" ]; then
  echo "$0 <host> [<repository>]"
  exit 1
fi

[ -z "$repository" ] && repository="git@github.com:piglop/initialize-website.git"

set -x

../authorize_key root@$host
ssh -t root@$host <<EOF
  apt-get update
  apt-get install -y git-core
  ssh-keyscan -H github.com >>~/.ssh/known_hosts
  git clone $repository
EOF

