#!/bin/sh

sudo apt-get remove -y rubygems
sudo apt-get install -y ruby

archive=rubygems-1.3.7.tgz
dir=`basename $archive .tgz`

cd $TMP
wget http://production.cf.rubygems.org/rubygems/$archive || exit 1

tar -xf $archive
cd $dir
sudo ruby setup.rb
cd ..
rm -r $archive $dir

[ -e ~/.gemrc ] || echo "gem: --bindir /usr/local/bin --no-ri --no-rdoc" >~/.gemrc
