#!/bin/sh

if [ "$USER" = "root" ]; then
  sudo=""
else
  sudo="sudo"
fi

cd /tmp
mkdir ree
cd ree

dir="ruby-enterprise-1.8.7-2011.03"
file="$dir.tar.gz"
url="http://rubyenterpriseedition.googlecode.com/files/$file"

[ -e "$file" ] || wget "$url"
[ -d "$dir" ] || tar -xvzf "$file"
cd "$dir"
./installer --auto /usr/local --no-dev-docs --dont-install-useful-gems
