#!/bin/sh

if [ "$USER" = "root" ]; then
  sudo=""
else
  sudo="sudo"
fi

$sudo apt-get install -y bash curl git-core || exit 1
$sudo apt-get install -y build-essential bison openssl libreadline5 libreadline5-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev || exit 1

curl http://rvm.beginrescueend.com/releases/rvm-install-head | $sudo bash

$sudo rvm install ree
$sudo rvm --default use ree
