#!/usr/bin/env ruby

def File.write(filename, content)
  File.open(filename, 'w') { |f| f.write content }
end

hostname = %x(hostname).strip
unless hostname =~ /\./
  raise "Hostname #{hostname.inspect} is not fully qualified. Fix /etc/hostname and run /etc/init.d/hostname.sh"
end

hosts = File.read("/etc/hosts")
if hosts =~ /([\d\.]+).*\s#{Regexp.escape hostname}(\s|\n)/
  hosts_ip = $1
  if hosts_ip == "127.0.1.1"
    raise "Invalid IP associated to #{hostname.inspect} in /etc/hosts: #{hosts_ip.inspect}. Use real IP."
  end
else
  raise "Hostname #{hostname.inspect} not found in /etc/hosts"
end

packages = %w(
  automake
  lvm2 ssh bridge-utils iproute iputils-arping
  ndisc6 python python-pyopenssl openssl
  python-pyparsing python-simplejson
  python-pyinotify python-pycurl socat
  paramiko
  make
  pandoc
  graphviz
  python-sphinx
)

system "aptitude", "install", "-y", *packages unless packages.empty?

def update_config(filename, match, replacement)
  config = File.read(filename)
  if config.sub! match, replacement and $& != replacement
    puts "Changing #{$&.inspect} to #{replacement.inspect} in #{filename.inspect}"
    backup_filename = filename + ".before_ganeti_install"
    unless File.exists? backup_filename
      File.rename(filename, backup_filename)
    end
    File.write(filename, config)
    true
  else
    false
  end
end

update_config "/etc/lvm/lvm.conf", /filter = \[.+\]/, 'filter = [ "r|/dev/cdrom|", "r|/dev/drbd[0-9]+|" ]'

unless system <<-EOF
  set -x
  cd /root
  git clone git://git.ganeti.org/ganeti.git --branch stable-2.4
  cd ganeti
  set -e
  ./autogen.sh
  ./configure --localstatedir=/var --sysconfdir=/etc
  make
  make install
  cp doc/examples/ganeti.initd /etc/init.d/ganeti
  update-rc.d ganeti defaults 20 80
  cp doc/examples/ganeti.cron /etc/cron.d/ganeti
EOF
  raise "ganeti build failed"
end

%w(
/etc/ganeti
/var/lib/ganeti
/var/log/ganeti
/srv/ganeti
/srv/ganeti/os
/srv/ganeti/export
).each do |dir|
  Dir.mkdir dir unless File.exists?(dir)
end

puts "Installation done. Now initialize the cluster. See http://docs.ganeti.org/ganeti/current/html/install.html#initializing-the-cluster"
