#!/bin/sh

set -e

apt-get install -y git-core </dev/null
key=`ssh-keyscan github.com`
grep "$key" ~/.ssh/known_hosts >/dev/null || echo "$key" >>~/.ssh/known_hosts
git clone git@github.com:ouvrages/initialize-website.git
cd initialize-website
git pull
