#!/bin/bash

if [ "$USER" == "root" ]; then
  sudo=""
else
  sudo="sudo"
fi

[ "$1" == "--reinstall" ] && reinstall=yes

$sudo apt-get remove -y nginx
$sudo apt-get install -y libcurl4-openssl-dev build-essential

which passenger-install-nginx-module >/dev/null || $sudo gem install passenger

if [ ! -e /opt/nginx/conf/nginx.conf -o "$reinstall" = "yes" ]; then
  $sudo passenger-install-nginx-module --auto --auto-download --prefix=/opt/nginx
fi

cat <<EOF >/opt/nginx/conf/rails.conf.sample
  server {
    listen 80;
    server_name www.yourhost.com;
    root /somewhere/public;   # <--- be sure to point to 'public'!
    passenger_enabled on;
  }
EOF

cat <<EOF >/etc/init.d/nginx
#! /bin/sh

### BEGIN INIT INFO
# Provides:          nginx
# Required-Start:    \$network
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the nginx web server
# Description:       starts nginx using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/nginx/sbin
DAEMON=/opt/nginx/sbin/nginx
NAME=nginx
DESC=nginx
PID=/var/run/nginx.pid

test -x \$DAEMON || exit 0

# Include nginx defaults if available
if [ -f /etc/default/nginx ] ; then
        . /etc/default/nginx
fi

set -e

case "\$1" in
  start)
        echo -n "Starting \$DESC: "
        start-stop-daemon --start --quiet --pidfile \$PID \
                --exec \$DAEMON -- \$DAEMON_OPTS
        echo "\$NAME."
        ;;
  stop)
        echo -n "Stopping \$DESC: "
        start-stop-daemon --stop --quiet --pidfile \$PID \
                --exec \$DAEMON
        echo "\$NAME."
        ;;
  restart|force-reload)
        echo -n "Restarting \$DESC: "
        start-stop-daemon --stop --quiet --pidfile \$PID \
                --exec \$DAEMON
        sleep 1
        start-stop-daemon --start --quiet --pidfile \$PID \
                --exec \$DAEMON -- \$DAEMON_OPTS
        echo "\$NAME."
        ;;
  reload)
      echo -n "Reloading \$DESC configuration: "
      start-stop-daemon --stop --signal HUP --quiet --pidfile \$PID \
          --exec \$DAEMON
      echo "\$NAME."
      ;;
  *)
        N=/etc/init.d/\$NAME
        echo "Usage: \$N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
EOF
$sudo chmod +x /etc/init.d/nginx

$sudo update-rc.d nginx defaults

$sudo ruby - /opt/nginx/conf/nginx.conf <<RUBY
  lines = [
    "server_names_hash_bucket_size 64;",
    "include sites/*.conf;"
  ].map { |line| " " * 4 + line + "\n" }.join
  data = File.read(ARGV.first)
  data.sub! /\s{4}#\}\n\n\}\n\Z/, "    #}\n\n#{lines}}\n"
  data.sub! "#pid        logs/nginx.pid;", "pid /var/run/nginx.pid;"
  File.open(ARGV.first, 'w') { |f| f.write data }
RUBY

[ -d /opt/nginx/conf/sites ] || $sudo mkdir /opt/nginx/conf/sites

if pidof nginx; then
  $sudo /etc/init.d/nginx restart
else
  $sudo /etc/init.d/nginx start
fi
