#!/bin/sh

if [ "$USER" == "root" ]; then
  sudo=""
else
  sudo="sudo"
fi

$sudo apt-get install -y ruby-dev build-essential libopenssl-ruby apache2-prefork-dev libapr1-dev libaprutil1-dev apache2-mpm-prefork libcurl4-openssl-dev

if [ ! -e /usr/lib/ruby/gems/1.8/gems/passenger-*/ext/apache2/mod_passenger.so ]; then
  which passenger-install-apache2-module >/dev/null || $sudo gem install passenger
  which rake >/dev/null || $sudo gem install rake
  $sudo ln -sf /usr/local/bin/rake /usr/bin/rake
  $sudo passenger-install-apache2-module --auto
fi

module=`ls /usr/lib/ruby/gems/1.8/gems/passenger-*/ext/apache2/mod_passenger.so`
root=`ls -d /usr/lib/ruby/gems/1.8/gems/passenger-* |tail -n 1`
ruby=`which ruby`

$sudo tee /etc/apache2/mods-available/passenger.load <<EOF
LoadModule passenger_module $module
PassengerRoot $root
PassengerRuby $ruby
EOF

$sudo tee /etc/apache2/mods-available/passenger.conf <<EOF
EOF

$sudo a2enmod passenger
$sudo /etc/init.d/apache2 restart

