#!/bin/sh

host="$1"
repository="$2"

if [ -z "$host" ]; then
  echo "$0 <user@host> [<repository>]"
  exit 1
fi

[ -z "$repository" ] && repository="git@github.com:piglop/initialize-website.git"

set -x

ssh -t $host <<EOF
  ssh-keyscan -H github.com >>~/.ssh/known_hosts
  git clone $repository
EOF

